version: 2.1
orbs:
  ship: auth0/ship@dev:b203467
jobs:
  build:
    environment:
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process
    docker:
      - image: cimg/android:2022.03.1

    steps:
      - checkout

      - run:
          name: Run checks
          command: ./gradlew clean test jacocoTestReport lint --continue --console=plain --max-workers=1 --no-daemon

      - store_artifacts:
          path: auth0/build/reports
          destination: reports

      - store_test_results:
          path: auth0/build/test-results

      - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
workflows:
  build-and-test:
    jobs:
      - build
      - ship/java-publish:
          prefix-tag: false
          publish-command: ./gradlew clean assemble publishAndroidLibraryPublicationToMavenRepository -PossrhUsername="$OSSR_USERNAME" -PossrhPassword="$OSSR_PASSWORD" -PisSnapshot=false
          context:
            - publish-gh
            - publish-sonatype
          filters:
            branches:
              only:
                - master
          requires:
            - build
