version: 2.1

orbs:
  ship: auth0/ship@dev:51f3320
  codecov: codecov/codecov@3
  
jobs:
  build:
    environment:
      GRADLE_OPTS: -Dkotlin.compiler.execution.strategy=in-process
    docker:
      - image: cimg/android:2022.03.1

    steps:
      - checkout

      - run:
          name: Run checks
          command: ./gradlew clean test jacocoTestReport lint --continue --console=plain --max-workers=1 --no-daemon

      - store_artifacts:
          path: auth0/build/reports
          destination: reports

      - store_test_results:
          path: auth0/build/test-results

      - codecov/upload

workflows:
  build-and-test:
    jobs:
      - build
      - ship/android-publish:
          prefix-tag: false
          package-group: com/auth0/android
          package-name: auth0
          publish-command: ./gradlew publishAndroidLibraryPublicationToMavenRepository -PossrhUsername="$OSSR_USERNAME" -PossrhPassword="$OSSR_PASSWORD" -PisSnapshot=false
          context:
            - publish-gh
            - publish-sonatype
          filters:
            branches:
              only:
                - main
          requires:
            - build
